spring:
  application:
    name: "configserver"

  profiles:
    active: native
  could:
    config:
      server:
        native:
          search-locations: "classpath:/config"



server:
  port: 8071